VQVAE:
  down_channels: [64, 128, 256, 256]
  mid_channels: [256, 256]
  down_sample: [True, True, True]
  num_down_layers: 2
  num_mid_layers: 2
  num_up_layers: 2
  attn_down: [False, False, False]
  z_channels: 3
  codebook_size: 8192
  norm_channels: 32
  num_heads: 4